version: '3.1'

services:
  web:
    build: .
    container_name: 'movie-ticket-web-api'
    restart: always
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html/'
      - './db:/var/www/html/db/'